### ISSUE TITLE
dll error

### ISSUE THREAD

**Issue by limelect** [tereshenkovav/PascalGameEngine#8]
![Screenshot - 07_07_2024 , 10_45_56](https://github.com/tereshenkovav/PascalGameEngine/assets/4199131/eb9aa441-47d0-4c64-a3a0-3eec42b608a3)

**Comment by tereshenkovav** [comment]
Hi, this is error with running example project from this repository, or other code?
Build with Delphi or FreePascal?

**Comment by limelect** [comment]
!Delphi example d10,2,3

**Comment by tereshenkovav** [comment]
After building exe-file in `example` dir, you must copy to `example` dir all dll files from csfml/Win32 (or csfml/Win64, if you build 64-bit app)
Also, in example dir must exists files `arial.ttf` and `logo.png`
If this conditions is OK, the example project must run successfull on any Windows machine with OpenGL 1.0 support

You can attach, if will, builded exe-file to issue, I test it.

**Comment by limelect** [comment]
to begin with, you only gave win32 dll
compiled for 32
Lastly, you are talking to a pro from Delphi #1 !!!!!

**Comment by limelect** [comment]
Every thing OK now

**Comment by tereshenkovav** [comment]
Missing 64bit dll in csfml dir - its my fault, plan fix it.

**Comment by tereshenkovav** [comment]
Fixed missing 64bit dlls and building script

https://github.com/tereshenkovav/PascalGameEngine/commit/298582220fe9c15b3845fd6b517c8edb99c55a9d
